<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? 'Safar Point Management' }}</title>
    <style>
        .table-wrap{overflow-x:auto}button:disabled{opacity:.55;cursor:not-allowed}
        :root{font-family:system-ui,-apple-system,sans-serif;color:#17202a;background:#f4f7f8}*{box-sizing:border-box}body{margin:0}header{background:#123b3a;color:white;padding:1rem 5vw;display:flex;justify-content:space-between;gap:1rem;align-items:center}nav{background:white;padding:.75rem 5vw;display:flex;gap:1rem;flex-wrap:wrap;border-bottom:1px solid #dce5e5}nav a{color:#123b3a;font-weight:600}.wrap{max-width:1200px;margin:2rem auto;padding:0 1rem}.panel{background:white;border:1px solid #dce5e5;border-radius:8px;padding:1.25rem;margin-bottom:1rem;overflow:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}label{display:grid;gap:.35rem;font-weight:600;margin-bottom:.8rem}input,textarea,select{font:inherit;padding:.65rem;border:1px solid #bacaca;border-radius:5px;width:100%}button{font:inherit;padding:.65rem 1rem;border:0;border-radius:5px;background:#e29b38;color:#17202a;font-weight:700;cursor:pointer}button.secondary{background:#dce5e5}button.danger{background:#c94c4c;color:white}table{border-collapse:collapse;width:100%;min-width:720px}th,td{text-align:left;padding:.7rem;border-bottom:1px solid #e5ecec;vertical-align:top}.error{color:#a52828}.status{color:#176b48}.logo{width:72px;height:72px;object-fit:cover;border-radius:50%;background:#e29b38;display:grid;place-items:center;font-size:1.5rem;font-weight:800;color:#123b3a}.actions{display:flex;gap:.5rem;flex-wrap:wrap}small{color:#607070}@media(max-width:640px){header{align-items:flex-start;flex-direction:column}.wrap{margin:1rem auto}}
    </style>
</head>
<body>
<header><strong>Safar Point Management</strong>@auth<form method="post" action="{{ route('logout') }}">@csrf<button class="secondary">Keluar</button></form>@endauth</header>
@auth<nav><a href="{{ route('dashboard') }}">Dashboard</a>@can('master-data.manage')<a href="{{ route('master-data.index', 'products') }}">Master Data</a>@endcan @can('users.view')<a href="{{ route('users.index') }}">Pengguna</a>@endcan @can('purchase-requests.create')<a href="{{ route('purchase-requests.index') }}">PR</a>@endcan @can('purchase-orders.create')<a href="{{ route('purchase-orders.index') }}">PO</a>@endcan @can('goods-receipts.create')<a href="{{ route('goods-receipts.index') }}">Penerimaan</a>@endcan @can('adjustments.create')<a href="{{ route('adjustments.index') }}">ADJ</a>@endcan @can('payments.create')<a href="{{ route('payments.index') }}">Pembayaran</a>@endcan @can('roles.manage')<a href="{{ route('roles.index') }}">Role & Permission</a>@endcan<a href="{{ route('audit.index') }}">Audit Aktivitas</a><a href="{{ route('settings.company') }}">Pengaturan</a></nav>@endauth
<main class="wrap">@if(session('status'))<p class="status">{{ session('status') }}</p>@endif @if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main>
</body></html>