@extends('layouts.app', ['title'=>'Purchase Request'])
@section('content')
<div class="page-header"><div><div class="breadcrumb">Purchasing / Purchase Request</div><h1>Purchase Request</h1><p>Buat dan pantau pengajuan kebutuhan pembelian.</p></div><button data-modal-open="create-pr"><x-icon name="plus"/> Buat PR</button></div>
<section class="panel"><div class="panel-header"><div><h2>Daftar Purchase Request</h2><p>Setiap PR menunggu persetujuan Owner/Direksi.</p></div></div><div class="toolbar"><label class="search-field">Cari PR<input type="search" placeholder="Cari nomor atau pemohon..." data-table-search="#pr-table"></label></div><div class="table-wrap" id="pr-table"><table><thead><tr><th>Nomor</th><th>Pemohon</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($requests as $item)<tr><td><strong>{{ $item->document_number??'Belum diterbitkan' }}</strong></td><td>{{ $item->requester->name }}</td><td><span class="status-badge {{ $item->status->value }}">{{ str_replace('_',' ',$item->status->value) }}</span></td><td><div class="actions">@if($item->status->value==='draft'&&$item->requester_id===auth()->id())<form method="post" action="{{ route('purchase-requests.submit',$item) }}">@csrf<button>Ajukan</button></form>@endif @if(auth()->user()->hasRole('Owner/Direksi')&&$item->status->value==='submitted')<form method="post" action="{{ route('purchase-requests.decide',$item) }}">@csrf<input type="hidden" name="decision" value="approved"><button>Setujui</button></form><form method="post" action="{{ route('purchase-requests.decide',$item) }}">@csrf<input type="hidden" name="decision" value="rejected"><button class="danger">Tolak</button></form>@endif</div></td></tr>
@empty<tr><td colspan="4"><div class="empty-state"><div class="empty-icon"><x-icon name="file"/></div><h3>Belum ada Purchase Request</h3><p>Buat PR pertama untuk memulai proses pembelian.</p></div></td></tr>@endforelse
</tbody></table></div>{{ $requests->links() }}</section>
<div class="modal" id="create-pr"><div class="modal-backdrop" data-modal-close></div><section class="drawer">
    <div class="drawer-header"><div><h2>Buat Purchase Request</h2><p>Simpan sebagai draft sebelum diajukan.</p></div><button class="icon-button" type="button" data-modal-close>×</button></div>
    <form method="post" action="{{ route('purchase-requests.store') }}">@csrf
        <div class="grid"><label>Departemen<input name="department" value="{{ old('department') }}" placeholder="Contoh: Operasional"></label><label>Prioritas<select name="priority"><option value="normal">Normal</option><option value="high">Tinggi</option><option value="low">Rendah</option></select></label></div>
        <label>Alasan Pengajuan<textarea name="reason" required placeholder="Jelaskan kebutuhan pembelian">{{ old('reason') }}</textarea></label>
        <label>Produk<div class="field-with-action"><select id="pr-product" name="items[0][product_id]" required><option value="">Pilih produk</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->sku }} — {{ $product->name }}{{ $product->barcode ? ' · '.$product->barcode : '' }}</option>@endforeach</select><button type="button" class="secondary scan-button" data-scan-trigger data-scan-mode="product" data-scan-target="#pr-product"><x-icon name="search"/> Scan SKU</button></div></label>
        <div class="grid"><label>Jumlah<input type="number" step="0.001" min="0.001" name="items[0][quantity]" required></label><label>Estimasi Harga Satuan<input type="number" step="0.01" min="0" name="items[0][estimated_price]" placeholder="Rp"></label></div>
        <div class="drawer-actions"><button class="outline" type="button" data-modal-close>Batal</button><button>Simpan Draft</button></div>
    </form>
</section></div>
@endsection
